### ISSUE TITLE
v1.2 -> 1.3 performance differences 

### ISSUE THREAD

**Issue by jamessimo** [iioinc/iio.js#26]
Looking through the the new 1.3 docs and demos and I am excited about the future of iioEngine, however I have to ask. Apart from the syntax changes and the new iioScript, is version 1.3 more efficient/performant at basic engine tasks? Like drawing frames, handling multiple objects, garbage collection etc.. 

Keep up the great work!

**Comment by sbiermanlytle** [comment]
Ok so ended up going in a different direction with v1.4.

(In the year that I was developing v1.3, iioScript was seperated from the JS library and became its own language that could be compiled into JavaScript. I still have plans for the language - you can see it in the v1.3 branch - but have been focusing exclusively on the JS library for iio.js v1.4)

Instead of passing string shorthand to a constructor, you must pass key value pairs:

```
app.add( new iio.Rectangle({
  pos: app.center,
  width: 80,
  color: 'blue',
  outline: 'red',
  lineWidth: 5,
});
```

Note that there is a similar 'best practice for performance' scenario in v1.4 that there was in v1.3:

```
obj.set({ color: 'black' }); // slightly less efficient

obj.color = iio.Color.black(); // slightly more efficient
```
slightly more work is done to interpret the set command, and convert `black` into an iio.Color object, but its really pretty negligible unless you are doing hundreds of these operations.

Also, I should point out:
```
obj.add( new iio...({...}); // automatically redraws
obj.add( new iio...({...}, true); // suppress the redraw
obj.set(... , true); // set also has a redraw suppress param
```
Make sure to suppress the redraw if you are adding more than one object at a time and the redraw is totally extraneous for any animated apps.
